from typing import List, Callable, Dict, Any, Optional


class WebModuleProtocol():
    web_pages: Dict[str, Dict[str, Any]]
    static_providers: Dict[str, Callable[[], List[str]]]

    def register_web_page(
        self, config: Dict[str, Any], provider: Callable[[], Any]
    ): ...
    def register_static_provider(
        self, prefix: str, provider: Callable[[], List[str]]
    ): ...
    def scan_and_register_providers(self, instance: Any): ...
    def get_web_pages_config(self, language: str = "en") -> List[Dict[str, Any]]: ...
    def get_docs_manifest(self) -> Dict[str, List[Dict[str, str]]]: ...
    def get_doc_path(self, doc_id: str) -> Optional[str]: ...
