from typing import List, Callable, Dict, Any, Optional, Protocol, runtime_checkable

@runtime_checkable
class WebPageProtocol(Protocol):

    """Protocol for components that provide a web page."""
    def get_web_page_config(self) -> Dict[str, Any]: ...
    async def render_page(self, request: Any, language: str = "en") -> Any: ...


@runtime_checkable
class WebOverrideProtocol(Protocol):
    """Protocol for components that override default web UI elements."""
    def get_landing_page_override(self) -> Optional[Dict[str, Any]]: ...
    def get_style_overrides(self) -> List[str]: ...
    def get_component_overrides(self) -> Dict[str, Any]: ...


@runtime_checkable
class StaticFilesProtocol(Protocol):
    """Protocol for components that provide static files."""
    def get_static_prefix(self) -> str: ...
    async def is_file_provided(self, path: str) -> bool: ...
    async def list_static_files(
        self, query: Optional[str] = None, limit: int = 100, offset: int = 0
    ) -> List[str]: ...


class WebModuleProtocol():
    web_pages: Dict[str, Dict[str, Any]]
    static_providers: Dict[str, Callable[..., Any]]

    def register_web_page(
        self, config: Dict[str, Any], provider: Callable[..., Any]
    ): ...
    def register_static_provider(
        self, prefix: str, provider: Callable[..., Any]
    ): ...
    async def get_web_pages_config(self, language: str = "en") -> List[Dict[str, Any]]: ...
    def get_web_page_content(self, page_id: str, request: Any, language: str = "en") -> Any: ...
    def get_docs_manifest(self) -> Dict[str, List[Dict[str, str]]]: ...
    def get_doc_path(self, doc_id: str) -> Optional[str]: ...
    def generate_etag(self, content_parts: List[bytes]) -> str: ...
    def get_cache_headers(self, max_age: int = 3600) -> Dict[str, str]: ...

