#    Copyright 2025 FAO
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
#    Author: Carlo Cancellieri (ccancellieri@gmail.com)
#    Company: FAO, Viale delle Terme di Caracalla, 00100 Rome, Italy
#    Contact: copyright@fao.org - http://fao.org/contact-us/terms/en/

"""DB-cleanup constants and SQL fragments — TEST-ONLY MODULE.

This module lives under ``tests/`` so it is **not packaged into the
production wheel**. Production-traffic code paths (FastAPI services,
ingestion / indexing / tiles jobs) cannot import this module — the
constants only exist when the source repository is checked out, e.g.
when the test suite runs locally / in CI.

The same constants are *also* needed at runtime by the operational
reset entrypoint ``dynastore.scripts.db_reset`` (invoked exclusively
by the ``Reset database (review only)`` Cloud Run job, never by API
traffic). That script keeps its own minimal copy of the same constants,
pinned by ``tests/.../test_db_cleanup_drift.py`` so the two
definitions cannot diverge.

What this file owns:

- the regex that identifies tenant schemas (``s_<8 base36>``);
- the canonical preserved-schema allowlist (system + platform schemas
  the reset must never drop);
- the canonical system-cron-job allowlist (jobs the reset must never wipe);
- the SQL for orphan-cron-job and orphan-GCS-bucket-record cleanup;
- the schema-batch size (PostgreSQL has a per-transaction
  ``max_locks_per_transaction`` limit; large drops need batching).

Connection handling stays caller-side — the test-suite cleanup uses
the dynastore SQLAlchemy engine; the reset script uses raw asyncpg —
both consume the same constants but never call the same connection
abstractions.
"""

from __future__ import annotations

from typing import FrozenSet, Iterable, Tuple


# ── Tenant-schema discovery ────────────────────────────────────────────────────

#: Regex that identifies a tenant schema generated by
#: :func:`dynastore.modules.catalog.catalog_service.generate_physical_name`.
#: ``s_`` followed by 8 base36 characters. Anchored. Both the cleanup
#: and the reset routines use this exact pattern.
TENANT_SCHEMA_PATTERN: str = r"^s_[0-9a-z]{8}$"

#: SQL parametrised on ``:pattern`` (or ``$1`` for asyncpg) returning every
#: tenant-schema name the reset / cleanup logic targets.
TENANT_SCHEMA_DISCOVERY_SQL: str = (
    "SELECT nspname FROM pg_namespace WHERE nspname ~ :pattern"
)

#: Same query but bind-by-position for asyncpg (uses ``$1``).
TENANT_SCHEMA_DISCOVERY_SQL_ASYNCPG: str = (
    "SELECT nspname FROM pg_namespace WHERE nspname ~ $1"
)


# ── Preserved schemas (full reset never drops these) ───────────────────────────

#: Schemas the full-reset path must NOT drop. Includes PostgreSQL system
#: schemas, the cron extension, public, the keycloak side table, the
#: Cloud SQL ML extension schemas (owned by the cloud SA, not the app
#: user), and the PostGIS topology extension.
DEFAULT_PRESERVED_SCHEMAS: FrozenSet[str] = frozenset({
    "pg_catalog",
    "information_schema",
    "pg_toast",
    "cron",
    "public",
    "keycloak",
    # Cloud SQL ML extension schemas — owned by the cloud SA, not the app user.
    "ai",
    "google_ml",
    # PostGIS topology extension.
    "topology",
})


# ── Cron-jobs allowlist (full reset must not wipe these) ───────────────────────

#: System cron jobs that survive a full reset. The reset wipes everything
#: NOT in this set so per-tenant scheduled jobs from a previous deployment
#: don't haunt the new schema.
DEFAULT_SYSTEM_CRON_JOBS: Tuple[str, ...] = (
    "system_cleanup_orphaned_cron_jobs",
    "monthly_cleanup_system_logs",
)


# ── Batch sizes / locks ────────────────────────────────────────────────────────

#: Number of schemas to DROP in a single transaction. PostgreSQL's
#: ``max_locks_per_transaction`` (default 64) caps how many ``ACCESS
#: EXCLUSIVE`` locks one transaction can hold; dropping more than ~20
#: schemas in one tx triggers ``out of shared memory``. The cleanup
#: path falls back to individual drops when a batch fails.
SCHEMA_DROP_BATCH_SIZE: int = 20


# ── SQL fragments shared by tests + reset script ───────────────────────────────

#: Truncate-on-cleanup tables that hold catalog-tier metadata. The
#: cleanup path truncates these; the full reset drops the schemas
#: outright so the truncate is a no-op there.
CATALOG_METADATA_TABLES: Tuple[str, ...] = ("catalogs", "collections")

#: SQL deleting GCP bucket records orphaned by tenant-schema drops.
#: Bind-friendly for both SQLAlchemy and asyncpg (no parameters).
DELETE_ORPHAN_GCP_BUCKET_RECORDS_SQL: str = (
    "DELETE FROM gcp.catalog_buckets "
    "WHERE catalog_id NOT IN (SELECT id FROM catalog.catalogs)"
)


# ── Helpers ────────────────────────────────────────────────────────────────────

def drop_schemas_batch_sql(schema_names: Iterable[str]) -> str:
    """Build a multi-statement string of ``DROP SCHEMA IF EXISTS`` calls.

    Used by the cleanup path to drop a batch of tenant schemas in one
    transaction. Each name is double-quoted so PostgreSQL does not
    fold-case or reject it; this function is a CONSTRUCTOR not a
    SANITISER — the caller MUST have validated names against
    :data:`TENANT_SCHEMA_PATTERN` (or another caller-known whitelist)
    before passing them in. Names that escaped the regex would inject
    SQL via the ``"..."`` quoting.
    """
    return "\n".join(f'DROP SCHEMA IF EXISTS "{s}" CASCADE;' for s in schema_names)
