#    Copyright 2025 FAO
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License. #    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 
#    Author: Carlo Cancellieri (ccancellieri@gmail.com)
#    Company: FAO, Viale delle Terme di Caracalla, 00100 Rome, Italy
#    Contact: copyright@fao.org - http://fao.org/contact-us/terms/en/

# dynastore/modules/styles/models.py

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, Optional, List, Union, Literal, Annotated

import html
from lxml import etree  # type: ignore[import]

from pydantic import BaseModel, Field, model_validator, ConfigDict, AliasChoices
from dynastore.models.shared_models import Link

class StyleFormatEnum(str, Enum):
    """Enumeration for supported style formats."""
    MAPBOX_GL = "MapboxGL"
    SLD_1_1 = "SLD_1.1"


class SLDContent(BaseModel):
    """Strongly-typed model for SLD 1.1 content."""
    format: Literal[StyleFormatEnum.SLD_1_1] = StyleFormatEnum.SLD_1_1
    sld_body: str = Field(..., description="A string containing the well-formed SLD XML document.")

    @model_validator(mode='before')
    @classmethod
    def validate_and_decode_sld(cls, data: Any) -> Any:
        """
        Validates that the 'sld_body' is well-formed XML and decodes HTML entities.
        """
        if isinstance(data, dict):
            sld_body = data.get('sld_body')
            if not isinstance(sld_body, str) or not sld_body.strip():
                raise ValueError("'sld_body' must be a non-empty string.")
            try:
                decoded_sld = html.unescape(sld_body)
                etree.fromstring(decoded_sld.encode('utf-8'))
                data['sld_body'] = decoded_sld # Mutate the dict with the cleaned version
            except etree.XMLSyntaxError as e:
                raise ValueError(f"Invalid SLD XML: The content is not well-formed. Error: {e}")
        return data

class MapboxContent(BaseModel):
    """
    Represents the content of a Mapbox GL Style. This is a placeholder
    and can be expanded with specific Mapbox style properties if needed.
    """
    model_config = ConfigDict(extra='allow')
    format: Literal[StyleFormatEnum.MAPBOX_GL] = StyleFormatEnum.MAPBOX_GL
    version: int = Field(..., description="Mapbox Style specification version.")
    sources: Dict[str, Any] = Field(..., description="Map sources.")
    layers: List[Dict[str, Any]] = Field(..., description="A list of style layers.")

class StyleSheetCreate(BaseModel):
    """A model for creating a new stylesheet, containing only the client-provided content."""
    content: Union[SLDContent, MapboxContent] = Field(..., discriminator='format', description="The style definition document, validated based on the format.")

class StyleSheet(BaseModel):
    """
    Represents a stylesheet, which is the representation of a style in a specific encoding.
    Aligned with OGC API - Styles spec section 7.4.6.
    This model includes the server-generated link and is used for responses.
    """
    # This is now a discriminated union. Pydantic will use the 'format' field
    # inside the JSON object to determine which model (SLDContent or MapboxContent) to use.
    content: Union[SLDContent, MapboxContent] = Field(..., discriminator='format')
    link: Link = Field(..., description="Link to the stylesheet resource, generated by the server.")

class StyleBase(BaseModel):
    """A base model containing the common metadata fields for a style."""
    style_id: str = Field(..., description="The identifier of the style. Unique within the collection.")
    title: Optional[str] = Field(None, description="A title for the style.")
    description: Optional[str] = Field(None, description="A description of the style.")
    keywords: Optional[List[str]] = Field(None, description="Keywords to help locate the style.")

class StyleCreate(StyleBase):
    """Model for creating a new style, aligned with OGC API - Styles. The user-facing 'id' is mapped to 'style_id'."""
    stylesheets: List[StyleSheetCreate] = Field(..., min_length=1, description="One or more stylesheet representations for this style.")

class StyleUpdate(BaseModel):
    """Model for updating an existing style."""
    title: Optional[str] = None
    description: Optional[str] = None
    keywords: Optional[List[str]] = None
    stylesheets: Optional[List[StyleSheetCreate]] = None

class Style(StyleBase):
    """Represents a full style record retrieved from the database."""
    id: uuid.UUID # The internal database UUID
    catalog_id: Annotated[str, Field(description="The catalog ID.")]
    collection_id: Annotated[str, Field(description="The collection ID.")]
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    stylesheets: List[StyleSheet] = Field(..., description="The list of available stylesheet representations for this style.")
    links: List[Link] = Field(default_factory=list, description="Links related to the style, including self-referencing links.")

    model_config = ConfigDict(from_attributes=True)
