#!/usr/bin/env bash
# Download FontAwesome 6.5.0 + Inter + Fira Code into web/static/vendor/
# so the web UI renders fully offline (on-prem docker compose, air-gapped
# Cloud Run). Generates a single vendor.css aggregator that HTML pages can
# drop in as a replacement for the CDN <link> tags.
#
# Swap in HTML:
#   - Replace   https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css
#   - Replace   https://fonts.googleapis.com/css2?family=Inter…
#   - With      /web/static/vendor/vendor.css
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
VENDOR="${REPO_DIR}/src/dynastore/extensions/web/static/vendor"
FA_VERSION="6.5.0"

mkdir -p "${VENDOR}/fontawesome/webfonts" "${VENDOR}/fonts"

echo "[1/3] FontAwesome ${FA_VERSION}…"
FA_ZIP="$(mktemp -t fa.zip.XXXXXX)"
curl -fsSL -o "${FA_ZIP}" \
    "https://use.fontawesome.com/releases/v${FA_VERSION}/fontawesome-free-${FA_VERSION}-web.zip"
TMP_DIR="$(mktemp -d)"
unzip -q "${FA_ZIP}" -d "${TMP_DIR}"
cp "${TMP_DIR}/fontawesome-free-${FA_VERSION}-web/css/all.min.css" "${VENDOR}/fontawesome/"
cp -r "${TMP_DIR}/fontawesome-free-${FA_VERSION}-web/webfonts/." "${VENDOR}/fontawesome/webfonts/"
rm -rf "${FA_ZIP}" "${TMP_DIR}"

# Google Fonts: fetch the CSS, then download each referenced woff2 and
# rewrite the CSS to point at local paths. Using a desktop UA gets woff2.
fetch_google_font() {
    local css_query="$1"
    local out_name="$2"
    local css_url="https://fonts.googleapis.com/css2?${css_query}"
    local tmp_css
    tmp_css="$(mktemp -t gfont.XXXXXX.css)"
    curl -fsSL -A "Mozilla/5.0 (X11; Linux x86_64) vendor-script" \
        -o "${tmp_css}" "${css_url}"

    # Extract woff2 URLs, download each, rewrite CSS
    while IFS= read -r url; do
        local fname
        fname="$(basename "${url%%\?*}")"
        curl -fsSL -o "${VENDOR}/fonts/${fname}" "${url}"
        # Replace the absolute URL with a relative one
        # shellcheck disable=SC2001
        sed -i.bak "s|${url}|./fonts/${fname}|g" "${tmp_css}"
    done < <(grep -oE "https://[^)]+\.woff2" "${tmp_css}" | sort -u)

    rm -f "${tmp_css}.bak"
    mv "${tmp_css}" "${VENDOR}/${out_name}"
}

echo "[2/3] Inter…"
fetch_google_font "family=Inter:wght@300;400;500;600;700&display=swap" "inter.css"

echo "[3/4] Fira Code…"
fetch_google_font "family=Fira+Code:wght@400;500&display=swap" "fira-code.css"

echo "[4/4] Montserrat…"
fetch_google_font "family=Montserrat:wght@300;400;500;600;700&display=swap" "montserrat.css"

# Aggregator — HTML pages include only this.
cat > "${VENDOR}/vendor.css" <<'EOF'
/* Aggregated vendored web fonts. Generated by scripts/vendor-web-fonts.sh. */
@import url("./fontawesome/all.min.css");
@import url("./inter.css");
@import url("./fira-code.css");
EOF

echo "Done. Assets in ${VENDOR}"
echo "Update HTML pages: replace CDN <link> tags with"
echo "    <link rel=\"stylesheet\" href=\"/web/static/vendor/vendor.css\"/>"
